### PR TITLE
Youtube downloader

### PR DESCRIPTION
**Pull request by chitholian**
This is a new feature for `Persepolis Download Manager`. It is very much useful for them who does not have an unlimited broadband connection to enjoy `youtube` videos.

Because most of the powerful Download Managers have this feature, I realized it's importance. Specially I (as a Linux user) cannot use IDM or FDM (I don't like Wine). I need to download a lot of media (basically audio of the video lectures / songs). I saw that an excellent DM found for Linux! Yes, it is PDM. But it cannot download youtube videos without help of other websites (e.g. savefrom.net).
So, I tried to add this feature to PDM; and of-course, I tested it on my machine and enjoying. 

I hope you will enjoy (and help to improve it further). Thanks to all of you.

### CODE REVIEW

**Comment by alireza-amirsamimi** [comment]
@chitholian Hello
Because of copyright laws, we can't add this feature to the persepolis's browser extension. But we'll try to add it to the GUI as plugin :)

**Comment by chitholian** [comment]
No, you need not add anything to the browser extension, this will work with the current version of browser browser extension.

**Comment by chitholian** [comment]
No, you need not add anything to the browser extension, this will work with the current version of the browser extension.

**Comment by alireza-amirsamimi** [comment]
Oh sorry!
 When you opened this pull request, I got your message with a bot in my  telegram messenger, and I thinked that is a feature request in [issues](http://github.com/persepolisdm/persepolis/issues)😄

After your second message I checked my github and I realised that it was a pull request! and not issue :)
Thank you chitholian. we must modify your codes for mac and windows. Your codes works on linux.
I accept this pull request after some checking and changing dependecies in our AUR repository.

**Comment by alireza-amirsamimi** [comment]
thanks :)

**Pull request merged**
