### PR TITLE
fix url form as filename

### PR DESCRIPTION
**Pull request by Monirzadeh**
some time filename contains characters like %20% etc. (URL form)
this commit decode filename if that is in URL form.

### CODE REVIEW

**Comment by JafarAkhondali** [comment]
@Monirzadeh Add-on causes this problem and it's already patched, we'll publish the new release soon.

**Comment by alireza-amirsamimi** [comment]
Hello
I have urllib on my system but I got this error:

```
AttributeError: module 'urllib' has no attribute 'unquote'
```

**Comment by Monirzadeh** [comment]
Hi
this conflict happens because of python version.
I change the code for Python 3.
Jafar Akhondali thinks this problem happen only for link come from add-ons but I'm not sure.
cheek again.

**Comment by JafarAkhondali** [comment]
@Monirzadeh We had the exact same problem when link sent from add-on that's why i sent a comment, but then after seeing the pull request i deleted my comment, thought you wont see it.

**Comment by alireza-amirsamimi** [comment]
Thank you @Monirzadeh 
I will accept your pull request , after modifying our AUR git package. because user must install python-urllib3.

**Pull request merged**
