### PR TITLE
setup.py is replaced by meson

### PR DESCRIPTION
**Pull request by alireza-amirsamimi**
You can install persepolis with this commads:

```
meson setup builddir
cd builddir
meson compile
sudo meson install
```

### CODE REVIEW

**Comment by alireza-amirsamimi** [comment]
@iFreilicht
Please check this pull request

**Review by morealaz — APPROVED** [review]
All things worked!!

**Review by iFreilicht — COMMENTED** [review]
This is awesome! To test this, I packaged persepolis at 0cd869bfa82a002ae7460806171c2a89d4cf65cc in nixpkgs, and this change greatly reduced the number of patches we had to apply!

See https://github.com/iFreilicht/nixpkgs/commit/45a9c07806938d92c837c2419bffd3dbf535824f if you're interested.

There is still [this check](https://github.com/persepolisdm/persepolis/blob/0cd869bfa82a002ae7460806171c2a89d4cf65cc/check_dependencies.py#L97-L107) that prevents this from neatly building on macOS, though:

```
if os.path.isdir(notifications_path):
```

This will always be false on macOS, as you're not setting `notifications_path` to any value. You could either skip this check, or set the value to an empty string on macOS.

Of course, there will issues at runtime (like notifications not working), but I think for now, it's enough if persepolis builds on macOS, and then we can look into fixing the runtime code.

**Review by iFreilicht — APPROVED** [review]

**Comment by alireza-amirsamimi** [comment]
Thank you, I'll fix that issue.

**Comment by alireza-amirsamimi** [comment]
> This is awesome! To test this, I packaged persepolis at 0cd869bfa82a002ae7460806171c2a89d4cf65cc in nixpkgs, and this change greatly reduced the number of patches we had to apply!
> 
> See https://github.com/iFreilicht/nixpkgs/commit/45a9c07806938d92c837c2419bffd3dbf535824f if you're interested.
> 
> There is still [this check](https://github.com/persepolisdm/persepolis/blob/0cd869bfa82a002ae7460806171c2a89d4cf65cc/check_dependencies.py#L97-L107) that prevents this from neatly building on macOS, though:
> 
> ```
> if os.path.isdir(notifications_path):
> ```
> 
> This will always be false on macOS, as you're not setting `notifications_path` to any value. You could either skip this check, or set the value to an empty string on macOS.
> 
> Of course, there will issues at runtime (like notifications not working), but I think for now, it's enough if persepolis builds on macOS, and then we can look into fixing the runtime code.

Thank you, I'll fix that issue.

**Pull request merged**
